from mongoengine import *

class Traits(EmbeddedDocument):
    # Restaurant
    italian = BooleanField()
    taverna = BooleanField()
    mexican = BooleanField()
    burngers = BooleanField()
    thai = BooleanField()
    chinese = BooleanField()
    french = BooleanField()
    sushi = BooleanField()
    asian = BooleanField()
    tapas = BooleanField()
    english = BooleanField()
    modern_greek = BooleanField()
    chef = BooleanField()
    traditional_greek = BooleanField()
    mezedes = BooleanField()
    cretan = BooleanField()
    grill_souvlaki = BooleanField()
    fish = BooleanField()
    homemade = BooleanField()
    exotic = BooleanField()
    vegetarian = BooleanField()
    beerfood = BooleanField()
    indian = BooleanField()
    turkish = BooleanField()
    molecular = BooleanField()
    crepes = BooleanField()
    healthy = BooleanField()
    big_portions = BooleanField()
    minimal_food = BooleanField()
    dirty = BooleanField()
    sharing = BooleanField()
    buffet = BooleanField()
    food_on_the_go = BooleanField()
    after_hours = BooleanField()
    brunch = BooleanField()
    latin = BooleanField()
    spicy = BooleanField()
    comforting = BooleanField()
    steakhouse = BooleanField()
    breakfast = BooleanField()

    # Bar
    dance = BooleanField()
    shots = BooleanField()
    cocktails = BooleanField()
    wine = BooleanField()
    pub = BooleanField()
    big_club = BooleanField()
    small = BooleanField()
    sitting = BooleanField()
    gigs = BooleanField()
    clean_drinks = BooleanField()
    face_control = BooleanField()
    sit_at_the_bar = BooleanField()
    hotel_bar = BooleanField()
    kername = BooleanField()
    shisha = BooleanField()
    raki_tsipouro = BooleanField()
    sports = BooleanField()
    gay_bar = BooleanField()

    # Coffee
    board_games = BooleanField()
    frapou = BooleanField()
    espresso_bar = BooleanField()
    coffee_on_the_go = BooleanField()
    work_and_study = BooleanField()
    big_cups = BooleanField()

    # Hood
    downtown = BooleanField()
    busy = BooleanField()
    underground = BooleanField()
    suburbs = BooleanField()
    by_the_sea = BooleanField()
    posh_hood = BooleanField()
    calm = BooleanField()
    touristic = BooleanField()
    corporate = BooleanField()

    # Space
    modern = BooleanField()
    prive = BooleanField()
    traditional = BooleanField()
    spacey = BooleanField()
    colourful = BooleanField()
    minimal = BooleanField()
    retro = BooleanField()
    concept = BooleanField()
    table_sharing = BooleanField()
    house_like = BooleanField()
    sofas = BooleanField()
    big_tables = BooleanField()
    cozy = BooleanField()
    crowded = BooleanField()
    great_view = BooleanField()
    terrace = BooleanField()
    open_air = BooleanField()
    garden = BooleanField()

    # Crowd
    kids = BooleanField()
    students = BooleanField()
    females = BooleanField()
    males = BooleanField()
    professionals = BooleanField()
    young_professionals = BooleanField()
    hipsters = BooleanField()
    old_people = BooleanField()
    hippies = BooleanField()
    indy = BooleanField()
    posh = BooleanField()
    couples = BooleanField()
    celebrities = BooleanField()
    singles = BooleanField()
    gay_lesbian = BooleanField()
    families = BooleanField()
    artists = BooleanField()
    musicians = BooleanField()

    # Ambience
    noisy = BooleanField()
    dark = BooleanField()
    beer_smell = BooleanField()
    smokey = BooleanField()
    romantic = BooleanField()
    candles = BooleanField()
    sexy = BooleanField()
    flashy = BooleanField()
    flirty = BooleanField()
    bright = BooleanField()
    clean = BooleanField()
    party = BooleanField()
    friendly = BooleanField()
    family_like = BooleanField()
    quiet = BooleanField()
    loud = BooleanField()
    chillout = BooleanField()

    # Music
    mainstream = BooleanField()
    rock = BooleanField()
    hip_hop = BooleanField()
    electronic = BooleanField()
    house = BooleanField()
    greek_pop = BooleanField()
    alternative = BooleanField()
    latin = BooleanField()
    jazz = BooleanField()
    eclectic = BooleanField()
    atmospheric = BooleanField()
    disco = BooleanField()
    oldschool = BooleanField()
    live = BooleanField()
    karaoke = BooleanField()
    goth = BooleanField()
    metal = BooleanField()
    heavy_greek = BooleanField()
    rebetika = BooleanField()
    funk_soul = BooleanField()
    loud = BooleanField()
    soft = BooleanField()
    radio = BooleanField()
    no_music = BooleanField()
    dj_based = BooleanField()